### ISSUE TITLE
Update `size()` mixin

### ISSUE THREAD

**Issue by carrieforde** [carrieforde/Aurora-Utilities#1]
Currently, we have:

```scss
@mixin size($width, $height) {
  @if not $height {
    $height: $width;
  }

  height: $height;
  width: $width;
}
```

This needs to updated & simplified by defaulting height to the width variable in the declaration, like so:

```scss
@mixin size($width, $height: $width) {}
```
